# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170102_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('enlaces', models.ManyToManyField(to='app.Enlace')),
            ],
        ),
    ]
