# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_agregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='imagen',
            field=models.ImageField(default='', upload_to='enlaces/'),
            preserve_default=False,
        ),
    ]
